spring:
  application:
    name: discovery
server:
  port: 9002
management:
  endpoints:
    web:
      cors:
        allowed-origins: ["health", "trace", "info", "metrics"]
eureka:
  instance:
    hostname: localhost
  client: 
    service-url:
      defaultZone: http://discoveryAdminName:discoveryAdminPwd@localhost:9002/eureka/
    register-with-eureka: false
    fetch-registry: false
