spring:
  application:
    name: gateway
zuul:
  ignored-services: "*"
  routes:
    api:
      path: "/api/**"
      sensitive-headers: [Set-Cookie, Authorization]
      service-id: api
      strip-prefix: true
    discovery:
      path: "/discovery/**"
      sensitive-headers: [Set-Cookie, Authorization]
      url: http://localhost:9002
server:
  port: 9003
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30
management:
  security:
    sessions: always
  endpoints:
    web:
      cors:
        allowed-origins: ["health", "trace", "info", "metrics"]
